### ISSUE TITLE
memos 更新到0.14.1 后，API 格式略有变化，能否更新一下 Raycast 拓展对应的配置？

### ISSUE THREAD

**Issue by fordchao** [JakeLaoyu/memos-raycast#8]
您好。
在使用 Raycast 的 memos 拓展，感觉很不错。
更新 memos 到 0.14.1后，memos 在 API 格式上，略有调整，比如之前叫 Open API，现在叫 Open ID，对应的 API 地址，变成了http://ip 地址/api/v1/memo?openId的编码，相比原来，多了一个 v1 。
更新后的地址，配置到 Raycast 后，可以继续成功发送，但是原来的绿色小点，变成了失败的红色小点。
不知道您是否有空，更新一下对应的提示配置呢？
祝好。

**Comment by JakeLaoyu** [comment]
最近比较繁忙，我会找个时间更新一下

**Comment by JakeLaoyu** [comment]
https://github.com/raycast/extensions/pull/7686

已提 MR，请等待合并。

**Comment by fordchao** [comment]
点赞👍

**Comment by puppyapple** [comment]
@JakeLaoyu 使用send memo form的时候 加了文件的话文件会发送失败，提示command_id unkown，是不是也是api变动了不兼容导致的，我是用的是0.14.1版本也不行

**Comment by JakeLaoyu** [comment]
@puppyapple  我排查一下

**Comment by JakeLaoyu** [comment]
> @JakeLaoyu 使用send memo form的时候 加了文件的话文件会发送失败，提示command_id unkown，是不是也是api变动了不兼容导致的，我是用的是0.14.1版本也不行

https://github.com/raycast/extensions/pull/8157

**Comment by puppyapple** [comment]
> 

@JakeLaoyu 赞👍效率
